In [ ]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/miniconda3/envs/da/lib/python3.12/site-packages (1.2.2)

In [ ]:
import os 
import requests 
import pandas as pd
from dotenv import load_dotenv
import time
import glob

load_dotenv()
# API_KEY = os.getenv("API_KEY")
APP_TOKEN = os.getenv("APP_TOKEN")
PAGE_NUMBER = 1
PAGE_SIZE = 1000
NUM_OF_PAGES = 29_700//PAGE_SIZE

for pn in range(1 , NUM_OF_PAGES + 1):
   url = (
      f"https://data.cityofnewyork.us/api/v3/views/833y-fsy8/query.json?"
      f"app_token={APP_TOKEN}"
      f"&pageNumber={pn}&pageSize={PAGE_SIZE}"
      f"&query=SELECT%20incident_key%2C%20occur_date%2C%20occur_time%2C%20boro%2C%20loc_of_occur_desc%2C%20precinct%2C%20jurisdiction_code%2C%20loc_classfctn_desc%2C%20location_desc%2C%20statistical_murder_flag%2C%20perp_age_group%2C%20perp_sex%2C%20perp_race%2C%20vic_age_group%2C%20vic_sex%2C%20vic_race%2C%20x_coord_cd%2C%20y_coord_cd%2C%20latitude%2C%20longitude%2C%20geocoded_column"
   )

   response = requests.get(url)
   print(response.status_code)
   data = response.json()
   df = pd.DataFrame(data)
   df.to_csv(f"../data/raw/nyc-shooting-incidents-{pn}.csv")
   time.sleep(5)

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

KeyboardInterrupt:

In [32]:

df = pd.DataFrame(data)
df.head(100)

,incident_key,occur_date,occur_time,boro,loc_of_occur_desc,precinct,jurisdiction_code,loc_classfctn_desc,location_desc,statistical_murder_flag,...,geocoded_column,:id,:version,:created_at,:updated_at,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer
0,298699604,2024-12-31T00:00:00.000,19:16:00,BROOKLYN,OUTSIDE,69,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.888761, ...",row-2r92-kchq.j732,rv-7bjq.c54g_652q,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,2,8,42,13827,5
1,298699604,2024-12-31T00:00:00.000,19:16:00,BROOKLYN,OUTSIDE,69,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.888761, ...",row-3err-u7gv.mddi,rv-jmbw~jwvw.ksv4,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,2,8,42,13827,5
2,298672096,2024-12-30T00:00:00.000,16:45:00,BRONX,OUTSIDE,47,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.865964, ...",row-vwjz_4bzc-96sb,rv-u2zi.ekyb.f7du,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,5,2,30,11605,29
3,298672097,2024-12-30T00:00:00.000,18:48:00,BROOKLYN,OUTSIDE,60,2,HOUSING,MULTI DWELL - PUBLIC HOUS,False,...,"{'type': 'Point', 'coordinates': [-73.981557, ...",row-p3fe-cggc.z3qs,rv-vd4r.5p4h_tdix,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,2,45,35,18183,21
4,298672096,2024-12-30T00:00:00.000,16:45:00,BRONX,OUTSIDE,47,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.865964, ...",row-je5d~pzuh~fqvx,rv-4idt_a6qg-gcwq,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,5,2,30,11605,29
5,298672094,2024-12-30T00:00:00.000,12:15:00,BRONX,OUTSIDE,52,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.878964, ...",row-c2qm~6nvj_gk96,rv-went-bu25_q7km,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,5,40,34,11605,24
6,298672096,2024-12-30T00:00:00.000,16:45:00,BRONX,OUTSIDE,47,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.865964, ...",row-5eq9_idsu_9wuh,rv-5d2q.99g4_sdum,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,5,2,30,11605,29
7,298672095,2024-12-30T00:00:00.000,20:32:00,BRONX,INSIDE,41,0,DWELLING,MULTI DWELL - APT BUILD,True,...,"{'type': 'Point', 'coordinates': [-73.899003, ...",row-36cm.bd2j.bx9h,rv-42f9_hk72~zf2e,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,5,43,25,10937,34
8,298628071,2024-12-29T00:00:00.000,17:24:00,MANHATTAN,OUTSIDE,23,0,STREET,(null),False,...,"{'type': 'Point', 'coordinates': [-73.946702, ...",row-uvf5.vqpj.n57p,rv-sr7c_2kwq_arp2,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,4,36,14,12426,7
9,298628070,2024-12-29T00:00:00.000,16:21:00,BRONX,OUTSIDE,43,0,STREET,(null),False,...,NaN,row-3rx3~mhef-bh3r,rv-vc9y.4esi_8mfw,2025-04-15T18:16:42.705Z,2025-04-15T18:16:46.643Z,NaN,NaN,NaN,NaN,NaN

In [41]:
files = glob.glob("../data/raw/*.csv")

dfs = [pd.read_csv(file) for file in files]
dfs

[     Unnamed: 0  incident_key               occur_date occur_time       boro  \
 0             0     209281500  2020-02-08T00:00:00.000   12:13:00     QUEENS
 1             1     209281497  2020-02-08T00:00:00.000   02:20:00   BROOKLYN
 2             2     209281498  2020-02-07T00:00:00.000   22:50:00   BROOKLYN
 3             3     209099251  2020-02-05T00:00:00.000   04:02:00     QUEENS
 4             4     209098666  2020-02-05T00:00:00.000   23:13:00  MANHATTAN
 ..          ...           ...                      ...        ...        ...
 995         995     193267668  2019-02-06T00:00:00.000   22:26:00   BROOKLYN
 996         996     193226256  2019-02-06T00:00:00.000   04:52:00   BROOKLYN
 997         997     193214568  2019-02-05T00:00:00.000   12:03:00     QUEENS
 998         998     193160951  2019-02-04T00:00:00.000   13:40:00   BROOKLYN
 999         999     193160952  2019-02-04T00:00:00.000   11:41:00   BROOKLYN

      precinct  jurisdiction_code  statistical_murder_flag perp_age_group  \
 0         115                0.0                     True          25-44
 1          76                0.0                     True          25-44
 2          75                0.0                    False          25-44
 3         101                0.0                    False            NaN
 4          34                0.0                    False          18-24
 ..        ...                ...                      ...            ...
 995        81                0.0                    False            NaN
 996        90                2.0                    False          25-44
 997       101                0.0                    False          18-24
 998        79                2.0                     True            NaN
 999        60                0.0                     True          25-44

     perp_sex  ...                 :id           :version  \
 0          M  ...  row-9gmn.z5yh-ft4a  rv-s83k_4298_b54h
 1          M  ...  row-ncsz~yif4-vx4z  rv-rdyu-65hg-vais
 2          M  ...  row-ua5k-uu5g_3c3z  rv-2p57_5gm3~je36
 3        NaN  ...  row-9fwp_fskh_4dpd  rv-j5p4.uzks.rtqm
 4          M  ...  row-4vzy~7aei-mmp7  rv-x246.nuvy_778g
 ..       ...  ...                 ...                ...
 995      NaN  ...  row-qri4-cx4n-9mpb  rv-m9tj.heiw-hwi3
 996        M  ...  row-czcg~83ut-mf25  rv-guqh.wtis.f4it
 997        M  ...  row-39vh-b57d~7qey  rv-gfy4-f7t8-76y2
 998      NaN  ...  row-uhap-kp3b~qczt  rv-2i9v-wgy4-znaz
 999        M  ...  row-kmk5_7cxd-bnci  rv-skq7_g955-r7jz

                   :created_at               :updated_at  \
 0    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 1    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 2    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 3    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 4    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 ..                        ...                       ...
 995  2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 996  2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 997  2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 998  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 999  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z

      :@computed_region_yeji_bk3q  :@computed_region_92fq_4b7q  \
 0                              3                           21
 1                              2                            7
 2                              2                           37
 3                              3                           47
 4                              4                           39
 ..                           ...                          ...
 995                            2                           49
 996                            2                           30
 997                            3                           47
 998                            2                           49
 999                            2                           45

      :@computed_region_sbqj_enih  :@computed_region_efsh_h5xi  \
 0                             73                      14510.0
 1                             48                      13514.0
 2                             47                      17214.0
 3                             59                      20529.0
 4                             22                      13098.0
 ..                           ...                          ...
 995                           52                      13516.0
 996                           56                      17213.0
 997                           59                      20529.0
 998                           51                      17618.0
 999                           35                      18184.0

     :@computed_region_f5dn_yrer              location_desc
 0                            65                        NaN
 1                            14                        NaN
 2                            45                        NaN
 3                            51    MULTI DWELL - APT BUILD
 4                            47    MULTI DWELL - APT BUILD
 ..                          ...                        ...
 995                          69                        NaN
 996                          36  MULTI DWELL - PUBLIC HOUS
 997                          51                        NaN
 998                          69  MULTI DWELL - PUBLIC HOUS
 999                          21                        NaN

 [1000 rows x 29 columns],
      Unnamed: 0  incident_key               occur_date occur_time      boro  \
 0             0     216463653  2020-08-12T00:00:00.000   01:20:00  BROOKLYN
 1             1     216458808  2020-08-11T00:00:00.000   21:30:00  BROOKLYN
 2             2     216458810  2020-08-11T00:00:00.000   22:45:00  BROOKLYN
 3             3     216458807  2020-08-11T00:00:00.000   16:44:00     BRONX
 4             4     216458279  2020-08-11T00:00:00.000   00:55:00  BROOKLYN
 ..          ...           ...                      ...        ...       ...
 995         995     209283225  2020-02-09T00:00:00.000   19:40:00  BROOKLYN
 996         996     209281503  2020-02-09T00:00:00.000   02:27:00     BRONX
 997         997     209281499  2020-02-08T00:00:00.000   05:30:00    QUEENS
 998         998     209281504  2020-02-08T00:00:00.000   22:06:00  BROOKLYN
 999         999     209281502  2020-02-08T00:00:00.000   20:28:00     BRONX

      precinct  jurisdiction_code  statistical_murder_flag perp_age_group  \
 0          77                  0                     True          25-44
 1          61                  0                     True          18-24
 2          70                  0                    False            NaN
 3          44                  0                    False            NaN
 4          78                  2                    False            NaN
 ..        ...                ...                      ...            ...
 995        77                  0                    False            NaN
 996        40                  2                     True          25-44
 997       103                  0                    False            NaN
 998        83                  0                    False          45-64
 999        41                  0                    False          45-64

     perp_sex  ...                 :id           :version  \
 0          M  ...  row-aqv3-gaq8-5gvz  rv-vptg~wt38_gphk
 1          M  ...  row-j5jd~ei8k.wngw  rv-tqut~fuxh~ktbj
 2        NaN  ...  row-93i2-hwug~6vre  rv-t6rw-tvqm.zm4x
 3        NaN  ...  row-kttd_ptu2.d65u  rv-9fqh~shfe-ee29
 4        NaN  ...  row-35td.6suy-zgg9  rv-9y9m_ufkm_b2d6
 ..       ...  ...                 ...                ...
 995      NaN  ...  row-36ek_naec-7fs4  rv-iicd-xd8m.qbd7
 996        M  ...  row-6nbb.52cn_czue  rv-86w6~wfji.ajnz
 997      NaN  ...  row-iq4p_af6v~g6b4  rv-2hkt~gzf5~5is2
 998        M  ...  row-g3dn-745r.6vfn  rv-qyd4_b6gt-quzc
 999        M  ...  row-hpfz~j2sk_jvr2  rv-hydw-5y8g~wq5s

                   :created_at               :updated_at  \
 0    2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 1    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 2    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 3    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 4    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 ..                        ...                       ...
 995  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 996  2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 997  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 998  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 999  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z

      :@computed_region_yeji_bk3q  :@computed_region_92fq_4b7q  \
 0                              2                           49
 1                              2                           15
 2                              2                           11
 3                              5                           35
 4                              2                           38
 ..                           ...                          ...
 995                            2                           49
 996                            5                           35
 997                            3                            6
 998                            2                           30
 999                            5                           43

      :@computed_region_sbqj_enih  :@computed_region_efsh_h5xi  \
 0                             49                      17615.0
 1                             36                      13826.0
 2                             43                      13510.0
 3                             27                      10930.0
 4                             54                      17619.0
 ..                           ...                          ...
 995                           49                      17618.0
 996                           23                      10932.0
 997                           61                      15312.0
 998                           53                      18181.0
 999                           24                      10937.0

     :@computed_region_f5dn_yrer              location_desc
 0                            16                        NaN
 1                            32                        NaN
 2                            60                        NaN
 3                            50                        NaN
 4                            68  MULTI DWELL - PUBLIC HOUS
 ..                          ...                        ...
 995                          16             BAR/NIGHT CLUB
 996                          49  MULTI DWELL - PUBLIC HOUS
 997                          41                        NaN
 998                          42                        NaN
 999                           8                        NaN

 [1000 rows x 29 columns],
      Unnamed: 0  incident_key               occur_date occur_time  \
 0             0      69643420  2010-01-06T00:00:00.000   13:50:00
 1             1      69581941  2010-01-05T00:00:00.000   20:20:00
 2             2      69576831  2010-01-04T00:00:00.000   19:10:00
 3             3      69526319  2010-01-03T00:00:00.000   18:10:00
 4             4      69526317  2010-01-03T00:00:00.000   05:16:00
 ..          ...           ...                      ...        ...
 995         995      63472900  2009-07-06T00:00:00.000   01:30:00
 996         996      63465788  2009-07-06T00:00:00.000   23:27:00
 997         997      63472883  2009-07-06T00:00:00.000   01:55:00
 998         998      63472883  2009-07-06T00:00:00.000   01:55:00
 999         999      63472901  2009-07-06T00:00:00.000   00:15:00

               boro  precinct  jurisdiction_code  statistical_murder_flag  \
 0    STATEN ISLAND       120                  0                    False
 1         BROOKLYN        73                  2                    False
 2         BROOKLYN        60                  2                    False
 3         BROOKLYN        66                  0                    False
 4            BRONX        47                  0                    False
 ..             ...       ...                ...                      ...
 995       BROOKLYN        75                  0                    False
 996       BROOKLYN        81                  0                    False
 997          BRONX        47                  0                    False
 998          BRONX        47                  0                     True
 999       BROOKLYN        83                  0                    False

     perp_age_group perp_sex  ...                 :id           :version  \
 0            18-24        M  ...  row-tbp9.p4y9-m29i  rv-8kfu_cy9q.f2w8
 1            18-24        M  ...  row-pvh4-wb7e_fxqz  rv-69hr-7gs3_cq36
 2            25-44        M  ...  row-eg2c-xh3u.8cwy  rv-s2bc~kwyn.fdjm
 3            25-44        M  ...  row-uzqu_hyuz-8gaa  rv-uyec-h9c9.9n69
 4          UNKNOWN        U  ...  row-4fwr-fy9w.d2ek  rv-enaf_22s6~3ug7
 ..             ...      ...  ...                 ...                ...
 995            NaN      NaN  ...  row-hucq~sgu6.8xiu  rv-hags_8g7r~3m7x
 996          18-24        M  ...  row-3afs_42ct.8erv  rv-hem4.8hn7.eh74
 997          25-44        M  ...  row-nmn7_dvvr_esmr  rv-q24n~r7ap.t5n2
 998          25-44        M  ...  row-q7xy_sbwk_8us9  rv-sjvf.e3xu_gfdf
 999        UNKNOWN        U  ...  row-7wi3.8nak_6zgk  rv-gnp6~b6ux-bq3k

                   :created_at               :updated_at  \
 0    2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 1    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 2    2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 3    2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 4    2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 ..                        ...                       ...
 995  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 996  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 997  2024-04-23T13:36:19.239Z  2024-04-23T13:36:30.560Z
 998  2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z
 999  2024-04-23T13:36:19.239Z  2024-04-23T13:36:34.986Z

      :@computed_region_yeji_bk3q  :@computed_region_92fq_4b7q  \
 0                              1                           13
 1                              2                           17
 2                              2                           45
 3                              2                           27
 4                              5                           22
 ..                           ...                          ...
 995                            2                           37
 996                            2                           49
 997                            5                            2
 998                            5                            2
 999                            2                           30

      :@computed_region_sbqj_enih  :@computed_region_efsh_h5xi  \
 0                             75                      10370.0
 1                             46                      17614.0
 2                             35                      18183.0
 3                             39                      17620.0
 4                             30                      11605.0
 ..                           ...                          ...
 995                           47                      17215.0
 996                           52                      13516.0
 997                           30                      11275.0
 998                           30                      11275.0
 999                           53                      18181.0

     :@computed_region_f5dn_yrer              location_desc
 0                             4                        NaN
 1                            55  MULTI DWELL - PUBLIC HOUS
 2                            21  MULTI DWELL - PUBLIC HOUS
 3                             2    MULTI DWELL - APT BUILD
 4                            29             BAR/NIGHT CLUB
 ..                          ...                        ...
 995                          45                        NaN
 996                          69    MULTI DWELL - APT BUILD
 997                          29                        NaN
 998                          29                        NaN
 999                          42                        NaN

 [1000 rows x 29 columns],
      Unnamed: 0  incident_key               occur_date occur_time      boro  \
 0             0      73702376  2010-07-16T00:00:00.000   01:03:00  BROOKLYN
 1             1      73711070  2010-07-16T00:00:00.000   21:09:00     BRONX
 2             2      73719656  2010-07-16T00:00:00.000   20:30:00  BROOKLYN
 3             3      73693319  2010-07-15T00:00:00.000   22:21:00  BROOKLYN
 4             4      73702377  2010-07-15T00:00:00.000   23:39:00     BRONX
 ..          ...           ...                      ...        ...       ...
 995         995      69729913  2010-01-08T00:00:00.000   23:35:00    QUEENS
 996         996      69729913  2010-01-08T00:00:00.000   23:35:00    QUEENS
 997         997      69708093  2010-01-08T00:00:00.000   13:20:00     BRONX
 998         998      69708092  2010-01-08T00:00:00.000   12:25:00     BRONX
 999         999      69665449  2010-01-07T00:00:00.000   04:38:00  BROOKLYN

      precinct  jurisdiction_code              location_desc  \
 0          73                  2  MULTI DWELL - PUBLIC HOUS
 1          46                  0                        NaN
 2          67                  0             SMALL MERCHANT
 3          83                  0                        NaN
 4          41                  0                        NaN
 ..        ...                ...                        ...
 995       114                  0                        NaN
 996       114                  0                        NaN
 997        46                  0                        NaN
 998        44                  0                        NaN
 999        77                  0                        NaN

      statistical_murder_flag vic_age_group  ...               :created_at  \
 0                      False         18-24  ...  2024-04-23T13:36:19.239Z
 1                      False         18-24  ...  2024-04-23T13:36:19.239Z
 2                      False           <18  ...  2024-04-23T13:36:19.239Z
 3                      False         45-64  ...  2024-04-23T13:36:19.239Z
 4                      False         18-24  ...  2024-04-23T13:36:19.239Z
 ..                       ...           ...  ...                       ...
 995                     True         45-64  ...  2024-04-23T13:36:19.239Z
 996                     True         45-64  ...  2024-04-23T13:36:19.239Z
 997                    False         18-24  ...  2024-04-23T13:36:19.239Z
 998                    False         25-44  ...  2024-04-23T13:36:19.239Z
 999                    False         25-44  ...  2024-04-23T13:36:19.239Z

                   :updated_at  :@computed_region_yeji_bk3q  \
 0    2024-04-23T13:36:34.986Z                            2
 1    2024-04-23T13:36:34.986Z                            5
 2    2024-04-23T13:36:34.986Z                            2
 3    2024-04-23T13:36:30.560Z                            2
 4    2024-04-23T13:36:30.560Z                            5
 ..                        ...                          ...
 995  2024-04-23T13:36:30.560Z                            3
 996  2024-04-23T13:36:30.560Z                            3
 997  2024-04-23T13:36:30.560Z                            5
 998  2024-04-23T13:36:30.560Z                            5
 999  2024-04-23T13:36:30.560Z                            2

      :@computed_region_92fq_4b7q  :@computed_region_sbqj_enih  \
 0                             17                           46
 1                             29                           29

In [ ]:

combined_df = pd.concat(dfs, ignore_index=True)

combined_df.to_csv("../data/processed/clean_data.csv", index=False)

clean_data.csv

In [44]:
combined_df

,Unnamed: 0,incident_key,occur_date,occur_time,boro,precinct,jurisdiction_code,statistical_murder_flag,perp_age_group,perp_sex,...,:created_at,:updated_at,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,location_desc,loc_of_occur_desc,loc_classfctn_desc
0,0,209281500,2020-02-08T00:00:00.000,12:13:00,QUEENS,115,0.0,True,25-44,M,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,3.0,21.0,73.0,14510.0,65.0,NaN,NaN,NaN
1,1,209281497,2020-02-08T00:00:00.000,02:20:00,BROOKLYN,76,0.0,True,25-44,M,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,2.0,7.0,48.0,13514.0,14.0,NaN,NaN,NaN
2,2,209281498,2020-02-07T00:00:00.000,22:50:00,BROOKLYN,75,0.0,False,25-44,M,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,2.0,37.0,47.0,17214.0,45.0,NaN,NaN,NaN
3,3,209099251,2020-02-05T00:00:00.000,04:02:00,QUEENS,101,0.0,False,NaN,NaN,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,3.0,47.0,59.0,20529.0,51.0,MULTI DWELL - APT BUILD,NaN,NaN
4,4,209098666,2020-02-05T00:00:00.000,23:13:00,MANHATTAN,34,0.0,False,18-24,M,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,4.0,39.0,22.0,13098.0,47.0,MULTI DWELL - APT BUILD,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28995,995,240338259,2022-02-09T00:00:00.000,00:45:00,BROOKLYN,75,0.0,True,(null),(null),...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,2.0,37.0,47.0,17215.0,45.0,PVT HOUSE,OUTSIDE,STREET
28996,996,240379307,2022-02-09T00:00:00.000,13:33:00,BROOKLYN,90,2.0,False,(null),(null),...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,2.0,30.0,56.0,17213.0,36.0,MULTI DWELL - PUBLIC HOUS,INSIDE,HOUSING
28997,997,240321242,2022-02-08T00:00:00.000,00:30:00,BRONX,48,0.0,False,(null),(null),...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,5.0,43.0,31.0,11269.0,35.0,(null),OUTSIDE,STREET
28998,998,240321668,2022-02-08T00:00:00.000,20:02:00,BROOKLYN,69,0.0,False,25-44,M,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,2.0,8.0,42.0,13827.0,5.0,(null),OUTSIDE,STREET
28999,999,240321668,2022-02-08T00:00:00.000,20:02:00,BROOKLYN,69,0.0,False,18-24,M,...,2024-04-23T13:36:19.239Z,2024-04-23T13:36:30.560Z,2.0,8.0,42.0,13827.0,5.0,(null),OUTSIDE,STREET